name: awami_test
description: "Test the font Awami Nastaliq in a custom buit flutter engine with Graphite2 built into Harfbuzz"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Awami
      fonts:
        # - asset: assets/fonts/AwamiNastaliqDebug-Regular4.ttf
        - asset: assets/fonts/AwamiNastaliq-Regular.ttf
    - family: Noto3
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-VariableFont_wght.ttf
    - family: Noto4
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu[wght].ttf
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/ScheherazadeNew-Regular.ttf
        # - asset: fonts/Scheherazade-Bold.ttf
        #   weight: 700